name: andrewMrubacky
favicon: null
layout_spectrum: 0.5840899718459696
typography_spectrum: 0.035249377600848675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6785752302967012
  lightness: 0.6918578180484474
  saturation: 0.2197311574127525
  rhythmicContrast: 0.8602736119646579
purpose: []
